name: Pick

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:

  Pick:
    env:
      LINETOKEN: ${{ secrets.LINETOKEN }}
      TW_API_KEY: ${{ secrets.TW_API_KEY }}
      TW_API_KEY_SECRET: ${{ secrets.TW_API_KEY_SECRET }}
      TW_API_TOKEN: ${{ secrets.TW_API_TOKEN }}
      TW_API_TOKEN_SECRET: ${{ secrets.TW_API_TOKEN_SECRET }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install twurl
      run: sudo gem install twurl
    - name: Run Pick
      run: php worker/pick.php
