name: Coin Summary push

on:
  schedule:
    # Every 6hour
    - cron: '0 */6 * * *'
  workflow_dispatch:
  
jobs:

  build:
    env:
      LINETOKEN: ${{ secrets.LINETOKEN }}
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose run ccxt

    - name: Run Summary
      run: php worker/summary.php
