name: Coin Summary push

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:

  build:
    env:
      LINETOKEN: ${{ secrets.LINETOKEN }}
      TW_API_KEY: ${{ secrets.TW_API_KEY }}
      TW_API_KEY_SECRET: ${{ secrets.TW_API_KEY_SECRET }}
      TW_API_TOKEN: ${{ secrets.TW_API_TOKEN }}
      TW_API_TOKEN_SECRET: ${{ secrets.TW_API_TOKEN_SECRET }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose run --rm ccxt

    # - name: Run Summary
    #   run: php worker/summary.php
    - name: Install twurl
      run: sudo gem install twurl
    - name: test
      run: twurl

