name: Coin Summary push

on:
  schedule:
    # Every 1hour
    - cron: '0 */1 * * *'
  workflow_dispatch:
  
jobs:

  build:
    env:
      LINETOKEN: ${{ secrets.LINETOKEN }}
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose run ccxt

    - name: Run coinone summary
      run: php coinone/summary.php
      
    - name: Run binance summary
      run: php binance/summary.php
