name: Today

on:
#   schedule:
#     - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:

  Today:
    env:
      LINETOKEN: ${{ secrets.LINETOKEN }}
      TW_API_KEY: ${{ secrets.TW_API_KEY }}
      TW_API_KEY_SECRET: ${{ secrets.TW_API_KEY_SECRET }}
      TW_API_TOKEN: ${{ secrets.TW_API_TOKEN }}
      TW_API_TOKEN_SECRET: ${{ secrets.TW_API_TOKEN_SECRET }}
      SLACK_WEBHOOK_URL : ${{ secrets.SLACK_WEBHOOK_URL }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install twurl
      run: sudo gem install twurl
    - name: Run Today
      run: php worker/today.php
